//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ImageInfo {
    
    private ImageInfoFileInfo[] fileInfoField;
    
    private string idField;
    
    private string nPagesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FileInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ImageInfoFileInfo[] FileInfo {
        get {
            return this.fileInfoField;
        }
        set {
            this.fileInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nPages {
        get {
            return this.nPagesField;
        }
        set {
            this.nPagesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ImageInfoFileInfo {
    
    private string fileNameField;
    
    private string dwFileNameField;
    
    private string typeField;
    
    private string lengthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dwFileName {
        get {
            return this.dwFileNameField;
        }
        set {
            this.dwFileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DWDocument {
    
    private DWDocumentFileInfos[] fileInfosField;
    
    private DWDocumentFileDatasFileDataEntry[][] fileDatasField;
    
    private DWDocumentSection[] sectionField;
    
    private string dW5BasketFileNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FileInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DWDocumentFileInfos[] FileInfos {
        get {
            return this.fileInfosField;
        }
        set {
            this.fileInfosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FileDataEntry", typeof(DWDocumentFileDatasFileDataEntry), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DWDocumentFileDatasFileDataEntry[][] FileDatas {
        get {
            return this.fileDatasField;
        }
        set {
            this.fileDatasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Section", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DWDocumentSection[] Section {
        get {
            return this.sectionField;
        }
        set {
            this.sectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DW5BasketFileName {
        get {
            return this.dW5BasketFileNameField;
        }
        set {
            this.dW5BasketFileNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DWDocumentFileInfos {
    
    private ImageInfo[][] imageInfosField;
    
    private ImageInfo[][] thumbnailInfosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ImageInfo", typeof(ImageInfo), IsNullable=false)]
    public ImageInfo[][] ImageInfos {
        get {
            return this.imageInfosField;
        }
        set {
            this.imageInfosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ImageInfo", typeof(ImageInfo), IsNullable=false)]
    public ImageInfo[][] ThumbnailInfos {
        get {
            return this.thumbnailInfosField;
        }
        set {
            this.thumbnailInfosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DWDocumentFileDatasFileDataEntry {
    
    private string dictionaryEntryKeyField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DictionaryEntryKey {
        get {
            return this.dictionaryEntryKeyField;
        }
        set {
            this.dictionaryEntryKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DWDocumentSection {
    
    private DWDocumentSectionMetadata[] metadataField;
    
    private DWDocumentSectionPage[] pageField;
    
    private string numberField;
    
    private string startPageField;
    
    private string dwguidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Metadata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DWDocumentSectionMetadata[] Metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Page", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DWDocumentSectionPage[] Page {
        get {
            return this.pageField;
        }
        set {
            this.pageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string startPage {
        get {
            return this.startPageField;
        }
        set {
            this.startPageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dwguid {
        get {
            return this.dwguidField;
        }
        set {
            this.dwguidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DWDocumentSectionMetadata {
    
    private string databasePropertiesField;
    
    private DWDocumentSectionMetadataSystemProperties[] systemPropertiesField;
    
    private DWDocumentSectionMetadataFieldProperties[] fieldPropertiesField;
    
    private DWDocumentSectionMetadataStoreProperties[] storePropertiesField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DatabaseProperties {
        get {
            return this.databasePropertiesField;
        }
        set {
            this.databasePropertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SystemProperties", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DWDocumentSectionMetadataSystemProperties[] SystemProperties {
        get {
            return this.systemPropertiesField;
        }
        set {
            this.systemPropertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FieldProperties", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DWDocumentSectionMetadataFieldProperties[] FieldProperties {
        get {
            return this.fieldPropertiesField;
        }
        set {
            this.fieldPropertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StoreProperties", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DWDocumentSectionMetadataStoreProperties[] StoreProperties {
        get {
            return this.storePropertiesField;
        }
        set {
            this.storePropertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DWDocumentSectionMetadataSystemProperties {
    
    private string docIDField;
    
    private string diskNoField;
    
    private string pageCountField;
    
    private string flagsField;
    
    private string storeUserField;
    
    private string offsetField;
    
    private string modificationUserField;
    
    private string storeDateTimeField;
    
    private string modificationDateTimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DocID {
        get {
            return this.docIDField;
        }
        set {
            this.docIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DiskNo {
        get {
            return this.diskNoField;
        }
        set {
            this.diskNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PageCount {
        get {
            return this.pageCountField;
        }
        set {
            this.pageCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Flags {
        get {
            return this.flagsField;
        }
        set {
            this.flagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StoreUser {
        get {
            return this.storeUserField;
        }
        set {
            this.storeUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ModificationUser {
        get {
            return this.modificationUserField;
        }
        set {
            this.modificationUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StoreDateTime {
        get {
            return this.storeDateTimeField;
        }
        set {
            this.storeDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ModificationDateTime {
        get {
            return this.modificationDateTimeField;
        }
        set {
            this.modificationDateTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DWDocumentSectionMetadataFieldProperties {
    
    private DWDocumentSectionMetadataFieldPropertiesDate[] dateField;
    
    private DWDocumentSectionMetadataFieldPropertiesTextVar[] textVarField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Date", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public DWDocumentSectionMetadataFieldPropertiesDate[] Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TextVar", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public DWDocumentSectionMetadataFieldPropertiesTextVar[] TextVar {
        get {
            return this.textVarField;
        }
        set {
            this.textVarField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DWDocumentSectionMetadataFieldPropertiesDate {
    
    private string fieldField;
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DWDocumentSectionMetadataFieldPropertiesTextVar {
    
    private string lengthField;
    
    private string fieldField;
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DWDocumentSectionMetadataStoreProperties {
    
    private string documentNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DocumentName {
        get {
            return this.documentNameField;
        }
        set {
            this.documentNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DWDocumentSectionPage {
    
    private DWDocumentSectionPageRendition[] renditionField;
    
    private string numberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rendition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DWDocumentSectionPageRendition[] Rendition {
        get {
            return this.renditionField;
        }
        set {
            this.renditionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DWDocumentSectionPageRendition {
    
    private DWDocumentSectionPageRenditionContent[] contentField;
    
    private DWDocumentSectionPageRenditionAnnotationDW4CheckSum[][] annotationField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Content", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DWDocumentSectionPageRenditionContent[] Content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("DW4CheckSum", typeof(DWDocumentSectionPageRenditionAnnotationDW4CheckSum), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DWDocumentSectionPageRenditionAnnotationDW4CheckSum[][] Annotation {
        get {
            return this.annotationField;
        }
        set {
            this.annotationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DWDocumentSectionPageRenditionContent {
    
    private string idField;
    
    private string pageNumberInFileField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pageNumberInFile {
        get {
            return this.pageNumberInFileField;
        }
        set {
            this.pageNumberInFileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DWDocumentSectionPageRenditionAnnotationDW4CheckSum {
    
    private string dwCheckSumField;
    
    private string dwDateField;
    
    private string dwTimeField;
    
    private string dwImageSizeField;
    
    private string dwSourceField;
    
    private string sourceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dwCheckSum {
        get {
            return this.dwCheckSumField;
        }
        set {
            this.dwCheckSumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dwDate {
        get {
            return this.dwDateField;
        }
        set {
            this.dwDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dwTime {
        get {
            return this.dwTimeField;
        }
        set {
            this.dwTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dwImageSize {
        get {
            return this.dwImageSizeField;
        }
        set {
            this.dwImageSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dwSource {
        get {
            return this.dwSourceField;
        }
        set {
            this.dwSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DWDocument", typeof(DWDocument))]
    [System.Xml.Serialization.XmlElementAttribute("ImageInfo", typeof(ImageInfo))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
